import Section from '@/components/Section';
import { Typography } from '@/components/Typography';

export default function IntroSection() {
  return (
    <Section backgroundColor="bg-base-100">
      <div className="col-span-2 text-left md:col-span-1">
        <Typography variant="h2">
          ecotowari is an initiative to tackle the waste generated by flyers
          through a mailbox sticker.
        </Typography>

        <Typography variant="p" lineBreak>
          With tests carried out all around Tokyo, we have seen reduction rates
          of over 99%.
        </Typography>

        <Typography variant="p">
          Our early supporters have received virtually 0 flyers. With a cute and
          efficient sticker working for you in the background, you know that the
          next time you will open your mailbox, it will be to see the mail that
          matters!
        </Typography>
      </div>
    </Section>
  );
}
