import { StatisticCard } from '@/components/card/StatisticCard';
import Section from '@/components/Section';
import { Typography } from '@/components/Typography';
import {
  totalStickers,
  waterSaved,
  electricitySaved,
  co2Saved,
  flyersReduced,
} from '../../helpers/calculationHelpers';
import {
  faHouseUser,
  faWater,
  faTree,
  faLightbulb,
  faCloud,
} from '@fortawesome/free-solid-svg-icons';

export default function StatisticsSection({ stickers }) {
  const router = { locale: 'en' };

  return (
    <Section className="grid-cols-1 gap-8" backgroundColor="bg-slate-50">
      <div className="col-span-1 text-left md:col-span-1">
        <Typography variant="h2" className="text-center" border>
          ecotowari in numbers
        </Typography>

        <Typography variant="p" lineBreak>
          A single ecotowari sticker helps reduce waste generated by brochures
          by 85 grammes per week on average (tests done in the Tokyo region). It
          might not seem like much in itself but imagine the impact that all the
          ecotowari stickers together are having...
        </Typography>

        <Typography variant="p">
          No need to imagine it! We have laid it out below in our real-time
          impact generator ↓
        </Typography>
      </div>

      <div className="grid gap-8 text-center lg:grid-cols-12">
        <div className="col-span-12 lg:col-span-4">
          <StatisticCard
            faIcon={faHouseUser}
            statistic={totalStickers(stickers)}
            description={
              router.locale === 'en' ? 'Stickers in place' : 'ステッカー使用数'
            }
          />
        </div>
        <div className="col-span-12 lg:col-span-4">
          <StatisticCard
            faIcon={faTree}
            statistic={flyersReduced(stickers)}
            unit="kg"
            description={
              router.locale === 'en'
                ? 'Paper waste reduced'
                : '削減されたチラシ'
            }
          />
        </div>
        <div className="col-span-12 lg:col-span-4">
          <StatisticCard
            faIcon={faLightbulb}
            statistic={electricitySaved(stickers)}
            unit="KWh"
            description={
              router.locale === 'en' ? 'Electricity saved' : '省エネルギー'
            }
          />
        </div>
        <div className="col-span-12 lg:col-span-4 lg:col-start-3 ">
          <StatisticCard
            faIcon={faWater}
            statistic={waterSaved(stickers)}
            unit="L"
            description={
              router.locale === 'en' ? 'Water saved' : 'リットルの水を節約'
            }
          />
        </div>
        <div className="col-span-12 lg:col-span-4">
          <StatisticCard
            faIcon={faCloud}
            statistic={co2Saved(stickers)}
            unit="kg-CO2e"
            description={router.locale === 'en' ? 'CO₂ saved' : '削減されたCO₂'}
          />
        </div>
      </div>
    </Section>
  );
}
